language: node_js
services:
- mongodb
node_js:
- lts/*
env:
- USE_OLDEST_NPM_VERSIONS=0
- USE_OLDEST_NPM_VERSIONS=1
before_install:
- |
  if [ $USE_OLDEST_NPM_VERSIONS -eq 1 ]
  then
    # Test against oldest allowed versions in package.json - Use sed to remove ^ characters
    sed -i 's/"\^/"/g' package.json
    npm i mongoose@5.0.0 reflect-metadata@0.1.12
  else
    npm i mongoose reflect-metadata
  fi
script:
- npm test
- npm run coveralls
deploy:
  provider: npm
  email: benedikt.huss@gmail.com
  skip_cleanup: true
  api_key:
    secure: ZRWIVSKkpzmfAdHumdrkVkpursZCP4Rz9l5g+fr9Tjm8yyAR536ohlycbhfjoPYyhPupXRAtWcishDsYzBGKmw7CAIs1XCmV5erIIe2i1zOhjtMYCgkH21h16BzqzD5oVZXd3bb0qL+nydbsje8ZiO5iac23GAQKLS2+mvniAPLZc7Qg3HMX5FjzzAzmA8tHBdDGsGCoFMAE3A3C9KHT74ujrtpMUYs036ulfrVJAI8InKDzqWnwx6JYAJiPiCzdGsb44ntwZ7DZ2Zxu/MZ1VWPljPos3nAk3UYeovSJwy57flzYk2qgKntfvsOpkycG4IWUQiw2wi5CX5lamZcrXFp86xANCSpm1HGC/VdvwS5MZn0BYcn2awgm34uQqbZpyWkEHV4Wf+F1Iv8ElAMXuZtZyHDLl0hYjsOy3UBTdwmKbgBwDzyytHOH5K2OZXq+IcVT95PzTuf6xmZkbEY2WWpNLlN4PLl3cLDdzLcIWRRAER3UDJDTOZAjEVfOhTlSugk02JjVfYbM1+plVeKsYWo/rJHgdOQ6AKW+O4pm6IGYHw8jAAYOB9T21nbNz/HPMHZ4PEVUKTMbzVWnnQwNsoxWYHfgwIXmLhmnLcv49ruQxz68Eks8qXs84E+N24ChKCUTmoAfxHDJj+Wg4TfkUZYjrqvtVuBgupwIGe00UDI=
  on:
    branches:
      only:
      - master
